"""Initial migration with all tables

Revision ID: 38317158bfe8
Revises: 
Create Date: 2025-08-06 21:40:16.721025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38317158bfe8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.Column('target_file_id', sa.String(length=36), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('validation_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_relationships')
    # ### end Alembic commands ###
